## 使用read_table 和 read_csv

In [3]:
import pandas as pd

In [5]:
order = pd.read_table('./exe/meal_order_info.csv',sep=',',encoding='gbk')
print(len(order))

945

In [6]:
order1 = pd.read_csv('./exe/meal_order_info.csv',
                    encoding='gbk')
print(len(order1))

945

In [7]:
order2 = pd.read_table('./exe/meal_order_info.csv',
                      sep = ';',encoding='gbk')
print(order2)

    info_id,"emp_id","number_consumers","mode","dining_table_id","dining_table_name","expenditure","dishes_count","accounts_payable","use_start_time","check_closed","lock_time","cashier_id","pc_id","order_number","org_id","print_doc_bill_num","lock_table_info","order_status","phone","name"
0    417,1442,4,NA,1501,1022,165,5,165,"2016/8/1 11...
1    301,1095,3,NA,1430,1031,321,6,321,"2016/8/1 11...
2    413,1147,6,NA,1488,1009,854,15,854,"2016/8/1 1...
3    415,1166,4,NA,1502,1023,466,10,466,"2016/8/1 1...
4    392,1094,10,NA,1499,1020,704,24,704,"2016/8/1 ...
5    381,1243,4,NA,1487,1008,239,7,239,"2016/8/1 13...
6    429,1452,4,NA,1501,1022,699,15,699,"2016/8/1 1...
7    433,1109,8,NA,1490,1011,511,14,511,"2016/8/1 1...
8    569,1143,6,NA,1488,1009,326,9,326,"2016/8/1 17...
9    655,1268,8,NA,1492,1013,263,10,263,"2016/8/1 1...
10   577,1150,7,NA,1492,1013,380,7,380,"2016/8/1 17...
11   622,1220,4,NA,1483,1004,164,7,164,"2016/8/1 17...
12   651,1593,3,NA,1485,1006,137,5,137,"2016/8/1 18...
13   694,1122,8,NA,1492,1013,819,10,819,"2016/8/1 1...
14   462,1187,7,NA,1490,1011,431,13,431,"2016/8/1 1...
15   458,1455,2,NA,1480,1001,700,14,700,"2016/8/1 1...
16   467,1213,10,NA,1495,1016,615,15,615,"2016/8/1 ...
17   562,1552,8,NA,1508,1029,366,7,366,"2016/8/1 19...
18   486,1156,7,NA,1492,1013,443,12,443,"2016/8/1 2...
19   517,1008,2,NA,1480,1001,294,7,294,"2016/8/1 21...
20   452,1114,8,NA,1492,1013,167,7,167,"2016/8/1 21...
21   448,1449,6,NA,1505,1026,609,14,609,"2016/8/1 2...
22   193,1084,3,NA,1401,1005,238,8,238,"2016/8/2 11...
23   166,986,2,NA,1402,1003,260,7,260,"2016/8/2 11:...
24   342,1450,2,NA,1402,1003,109,5,109,"2016/8/2 11...
25   260,990,4,NA,1421,1022,302,9,302,"2016/8/2 12:...
26   367,1119,4,NA,1483,1004,639,13,639,"2016/8/2 1...
27   368,1125,4,NA,1500,1021,211,6,211,"2016/8/2 13...
28   365,992,2,NA,460,1002,146,6,146,"2016/8/2 13:1...
29   171,1463,3,NA,1403,1004,299,10,299,"2016/8/2 1...
..                                                 ...
915  387,1095,8,NA,1490,1011,551,16,551,"2016/8/30 ...
916  168,990,2,NA,1402,1003,1105,9,1105,"2016/8/30 ...
917  446,1166,2,NA,1482,1003,143,6,143,"2016/8/30 1...
918  735,1132,2,NA,1481,1002,270,8,270,"2016/8/30 1...
919  671,1084,2,NA,1482,1003,163,8,163,"2016/8/30 1...
920  603,1102,3,NA,1485,1006,459,11,459,"2016/8/30 ...
921  661,1096,8,NA,1492,1013,812,13,812,"2016/8/30 ...
922  565,1105,6,NA,1489,1010,717,8,717,"2016/8/30 2...
923  539,1110,10,NA,1519,1040,238,6,238,"2016/8/30 ...
924  636,1089,2,NA,1480,1001,349,9,349,"2016/8/30 2...
925  461,1075,3,NA,1484,1005,303,8,303,"2016/8/30 2...
926  777,1076,7,NA,1491,1012,824,24,824,"2016/8/30 ...
927  515,1161,2,NA,1482,1003,143,5,143,"2016/8/30 2...
928  289,991,2,NA,1402,1003,121,5,121,"2016/8/31 11...
929  419,1071,6,NA,1489,1010,264,6,264,"2016/8/31 1...
930  395,1021,4,NA,1485,1006,617,13,617,"2016/8/31 ...
931  411,1097,4,NA,1485,1006,214,2,214,"2016/8/31 1...
932  336,996,2,NA,1406,1007,131,5,131,"2016/8/31 13...
933  507,1128,8,NA,1506,1027,474,10,474,"2016/8/31 ...
934  763,1135,4,NA,1484,1005,296,7,296,"2016/8/31 1...
935  599,1102,8,NA,1491,1012,729,19,729,"2016/8/31 ...
936  721,1129,6,NA,1486,1007,624,15,624,"2016/8/31 ...
937  533,1118,1,NA,1482,1003,717,11,717,"2016/8/31 ...
938  551,1086,8,NA,1519,1040,1101,19,1101,"2016/8/3...
939  695,1096,6,NA,1486,1007,810,16,810,"2016/8/31 ...
940  641,1095,8,NA,1492,1013,679,12,679,"2016/8/31 ...
941  672,1089,6,NA,1489,1010,800,24,800,"2016/8/31 ...
942  692,1155,8,NA,1492,1013,735,10,735,"2016/8/31 ...
943  647,1094,4,NA,1485,1006,262,9,262,"2016/8/31 2...
944  570,1113,8,NA,1517,1038,589,13,589,"2016/8/31 ...

[945 rows x 1 columns]

In [8]:
order3 = pd.read_csv('./exe/meal_order_info.csv',
                    sep=',',header=None,encoding='gbk')
print(order3)

          0       1                 2     3                4   \
0    info_id  emp_id  number_consumers  mode  dining_table_id
1        417    1442                 4   NaN             1501
2        301    1095                 3   NaN             1430
3        413    1147                 6   NaN             1488
4        415    1166                 4   NaN             1502
5        392    1094                10   NaN             1499
6        381    1243                 4   NaN             1487
7        429    1452                 4   NaN             1501
8        433    1109                 8   NaN             1490
9        569    1143                 6   NaN             1488
10       655    1268                 8   NaN             1492
11       577    1150                 7   NaN             1492
12       622    1220                 4   NaN             1483
13       651    1593                 3   NaN             1485
14       694    1122                 8   NaN             1492
15       462    1187                 7   NaN             1490
16       458    1455                 2   NaN             1480
17       467    1213                10   NaN             1495
18       562    1552                 8   NaN             1508
19       486    1156                 7   NaN             1492
20       517    1008                 2   NaN             1480
21       452    1114                 8   NaN             1492
22       448    1449                 6   NaN             1505
23       193    1084                 3   NaN             1401
24       166     986                 2   NaN             1402
25       342    1450                 2   NaN             1402
26       260     990                 4   NaN             1421
27       367    1119                 4   NaN             1483
28       368    1125                 4   NaN             1500
29       365     992                 2   NaN              460
..       ...     ...               ...   ...              ...
916      387    1095                 8   NaN             1490
917      168     990                 2   NaN             1402
918      446    1166                 2   NaN             1482
919      735    1132                 2   NaN             1481
920      671    1084                 2   NaN             1482
921      603    1102                 3   NaN             1485
922      661    1096                 8   NaN             1492
923      565    1105                 6   NaN             1489
924      539    1110                10   NaN             1519
925      636    1089                 2   NaN             1480
926      461    1075                 3   NaN             1484
927      777    1076                 7   NaN             1491
928      515    1161                 2   NaN             1482
929      289     991                 2   NaN             1402
930      419    1071                 6   NaN             1489
931      395    1021                 4   NaN             1485
932      411    1097                 4   NaN             1485
933      336     996                 2   NaN             1406
934      507    1128                 8   NaN             1506
935      763    1135                 4   NaN             1484
936      599    1102                 8   NaN             1491
937      721    1129                 6   NaN             1486
938      533    1118                 1   NaN             1482
939      551    1086                 8   NaN             1519
940      695    1096                 6   NaN             1486
941      641    1095                 8   NaN             1492
942      672    1089                 6   NaN             1489
943      692    1155                 8   NaN             1492
944      647    1094                 4   NaN             1485
945      570    1113                 8   NaN             1517

                    5            6             7                 8   \
0    dining_table_name  expenditure  dishes_count  accounts_payable
1                 1022          165             5               165
2                 1031          321             6               321
3                 1009          854            15               854
4                 1023          466            10               466
5                 1020          704            24               704
6                 1008          239             7               239
7                 1022          699            15               699
8                 1011          511            14               511
9                 1009          326             9               326
10                1013          263            10               263
11                1013          380             7               380
12                1004          164             7               164
13                1006          137             5               137
14                1013          819            10               819
15                1011          431            13               431
16                1001          700            14               700
17                1016          615            15               615
18                1029          366             7               366
19                1013          443            12               443
20                1001          294             7               294
21                1013          167             7               167
22                1026          609            14               609
23                1005          238             8               238
24                1003          260             7               260
25                1003          109             5               109
26                1022          302             9               302
27                1004          639            13               639
28                1021          211             6               211
29                1002          146             6               146
..                 ...          ...           ...               ...
916               1011          551            16               551
917               1003         1105             9              1105
918               1003          143             6               143
919               1002          270             8               270
920               1003          163             8               163
921               1006          459            11               459
922               1013          812            13               812
923               1010          717             8               717
924               1040          238             6               238
925               1001          349             9               349
926               1005          303             8               303
927               1012          824            24               824
928               1003          143             5               143
929               1003          121             5               121
930               1010          264             6               264
931               1006          617            13               617
932               1006          214             2               214
933               1007          131             5               131
934               1027          474            10               474
935               1005          296             7               296
936               1012          729            19               729
937               1007          624            15               624
938               1003          717            11               717
939               1040         1101            19              1101
940               1007          810            16               810
941               1013          679            12               679
942               1010          800            24               800
943               1013          735            10               735
944               1006          262             9               262
945               1038          589            13               589

                     9   ...                   11          12     13  \
0        use_start_time  ...            lock_time  cashier_id  pc_id
1     2016/8/1 11:05:36  ...    2016/8/1 11:11:46         NaN    NaN
2     2016/8/1 11:15:57  ...    2016/8/1 11:31:55         NaN    NaN
3     2016/8/1 12:42:52  ...    2016/8/1 12:54:37         NaN    NaN
4     2016/8/1 12:51:38  ...    2016/8/1 13:08:20         NaN    NaN
5     2016/8/1 12:58:44  ...    2016/8/1 13:07:16         NaN    NaN
6     2016/8/1 13:15:42  ...    2016/8/1 13:23:42         NaN    NaN
7     2016/8/1 13:17:37  ...    2016/8/1 13:34:18         NaN    NaN
8     2016/8/1 13:38:27  ...    2016/8/1 13:50:16         NaN    NaN
9     2016/8/1 17:06:20  ...    2016/8/1 17:18:20         NaN    NaN
10    2016/8/1 17:32:27  ...    2016/8/1 17:44:27         NaN    NaN
11    2016/8/1 17:37:07  ...    2016/8/1 17:50:02         NaN    NaN
12    2016/8/1 17:40:18  ...    2016/8/1 17:47:08         NaN    NaN
13    2016/8/1 18:12:20  ...    2016/8/1 18:20:12         NaN    NaN
14    2016/8/1 18:26:27  ...    2016/8/1 18:37:27         NaN    NaN
15    2016/8/1 18:45:27  ...    2016/8/1 18:49:42         NaN    NaN
16    2016/8/1 19:27:29  ...    2016/8/1 19:31:41         NaN    NaN
17    2016/8/1 19:40:00  ...                  NaN         NaN    NaN
18    2016/8/1 19:44:56  ...    2016/8/1 19:57:51         NaN    NaN
19    2016/8/1 20:31:37  ...    2016/8/1 20:36:28         NaN    NaN
20    2016/8/1 21:11:44  ...    2016/8/1 21:21:12         NaN    NaN
21    2016/8/1 21:19:16  ...    2016/8/1 21:29:48         NaN    NaN
22    2016/8/1 21:37:26  ...    2016/8/1 21:52:56         NaN    NaN
23    2016/8/2 11:20:59  ...    2016/8/2 11:33:41         NaN    NaN
24    2016/8/2 11:22:19  ...    2016/8/2 11:30:19         NaN    NaN
25    2016/8/2 11:58:57  ...    2016/8/2 12:10:08         NaN    NaN
26    2016/8/2 12:35:59  ...    2016/8/2 12:53:59         NaN    NaN
27    2016/8/2 12:58:38  ...    2016/8/2 13:17:56         NaN    NaN
28    2016/8/2 13:08:42  ...    2016/8/2 13:22:42         NaN    NaN
29    2016/8/2 13:19:35  ...    2016/8/2 13:29:35         NaN    NaN
..                  ...  ...                  ...         ...    ...
916  2016/8/30 12:00:38  ...   2016/8/30 12:12:38         NaN    NaN
917  2016/8/30 12:07:06  ...   2016/8/30 12:19:06         NaN    NaN
918  2016/8/30 18:06:04  ...   2016/8/30 18:15:04         NaN    NaN
919  2016/8/30 18:13:05  ...   2016/8/30 18:18:05         NaN    NaN
920  2016/8/30 19:25:05  ...   2016/8/30 19:44:05         NaN    NaN
921  2016/8/30 19:30:19  ...   2016/8/30 19:45:19         NaN    NaN
922  2016/8/30 20:00:10  ...   2016/8/30 20:18:10         NaN    NaN
923  2016/8/30 20:14:52  ...   2016/8/30 20:30:52         NaN    NaN
924  2016/8/30 20:30:53  ...   2016/8/30 20:43:53         NaN    NaN
925  2016/8/30 20:52:16  ...   2016/8/30 21:10:36         NaN    NaN
926  2016/8/30 21:46:40  ...   2016/8/30 21:56:40         NaN    NaN
927  2016/8/30 21:49:55  ...   2016/8/30 21:59:55         NaN    NaN
928  2016/8/30 21:57:30  ...   2016/8/30 22:00:10         NaN    NaN
929  2016/8/31 11:52:44  ...   2016/8/31 12:01:38         NaN    NaN
930  2016/8/31 12:19:41  ...   2016/8/31 12:29:41         NaN    NaN
931  2016/8/31 12:51:51  ...   2016/8/31 13:02:38         NaN    NaN
932  2016/8/31 13:29:29  ...                  NaN         NaN    NaN
933  2016/8/31 13:59:05  ...   2016/8/31 14:06:37         NaN    NaN
934  2016/8/31 17:50:02  ...   2016/8/31 18:00:51         NaN    NaN
935  2016/8/31 18:05:01  ...   2016/8/31 18:09:40         NaN    NaN
936  2016/8/31 18:05:51  ...   2016/8/31 18:18:31         NaN    NaN
937  2016/8/31 18:28:06  ...   2016/8/31 18:42:42         NaN    NaN
938  2016/8/31 18:40:56  ...   2016/8/31 18:57:56         NaN    NaN
939  2016/8/31 19:14:12  ...   2016/8/31 19:19:31         NaN    NaN
940  2016/8/31 20:25:16  ...   2016/8/31 20:39:13         NaN    NaN
941  2016/8/31 21:23:48  ...   2016/8/31 21:31:48         NaN    NaN
942  2016/8/31 21:24:12  ...   2016/8/31 21:56:12         NaN    NaN
943  2016/8/31 21:25:18  ...   2016/8/31 21:33:34         NaN    NaN
944  2016/8/31 21:37:39  ...   2016/8/31 21:55:39         NaN    NaN
945  2016/8/31 21:41:56  ...   2016/8/31 21:32:56         NaN    NaN

               14      15                  16               17            18  \
0    order_number  org_id  print_doc_bill_num  lock_table_info  order_status
1             NaN     330                 NaN              NaN             1
2             NaN     328                 NaN              NaN             1
3             NaN     330                 NaN              NaN             1
4             NaN     330                 NaN              NaN             1
5             NaN     330                 NaN              NaN             1
6             NaN     330                 NaN              NaN             1
7             NaN     330                 NaN              NaN             1
8             NaN     330                 NaN              NaN             1
9             NaN     330                 NaN              NaN             1
10            NaN     330                 NaN              NaN             1
11            NaN     330                 NaN              NaN             1
12            NaN     330                 NaN              NaN             1
13            NaN     330                 NaN              NaN             1
14            NaN     330                 NaN              NaN             1
15            NaN     330                 NaN              NaN             1
16            NaN     330                 NaN              NaN             1
17            NaN     330                 NaN              NaN             0
18            NaN     330                 NaN              NaN             1
19            NaN     330                 NaN              NaN             1
20            NaN     330                 NaN              NaN             1
21            NaN     330                 NaN              NaN             1
22            NaN     330                 NaN              NaN             1
23            NaN     328                 NaN              NaN             1
24            NaN     328                 NaN              NaN             1
25            NaN     328                 NaN              NaN             1
26            NaN     328                 NaN              NaN             1
27            NaN     330                 NaN              NaN             1
28            NaN     330                 NaN              NaN             1
29            NaN     304                 NaN              NaN             1
..            ...     ...                 ...              ...           ...
916           NaN     330                 NaN              NaN             1
917           NaN     328                 NaN              NaN             1
918           NaN     330                 NaN              NaN             1
919           NaN     330                 NaN              NaN             1
920           NaN     330                 NaN              NaN             1
921           NaN     330                 NaN              NaN             1
922           NaN     330                 NaN              NaN             1
923           NaN     330                 NaN              NaN             1
924           NaN     330                 NaN              NaN             1
925           NaN     330                 NaN              NaN             1
926           NaN     330                 NaN              NaN             1
927           NaN     330                 NaN              NaN             1
928           NaN     330                 NaN              NaN             1
929           NaN     328                 NaN              NaN             1
930           NaN     330                 NaN              NaN             1
931           NaN     330                 NaN              NaN             1
932           NaN     330                 NaN              NaN             0
933           NaN     328                 NaN              NaN             1
934           NaN     330                 NaN              NaN             2
935           NaN     330                 NaN              NaN             1
936           NaN     330                 NaN              NaN             1
937           NaN     330                 NaN              NaN             1
938           NaN     330                 NaN              NaN             1
939           NaN     330                 NaN              NaN             1
940           NaN     330                 NaN              NaN             1
941           NaN     330                 NaN              NaN             1
942           NaN     330                 NaN              NaN             1
943           NaN     330                 NaN              NaN             1
944           NaN     330                 NaN              NaN             1
945           NaN     330                 NaN              NaN             1

              19    20
0          phone  name
1    18688880641   苗宇怡
2    18688880174    赵颖
3    18688880276   徐毅凡
4    18688880231   张大鹏
5    18688880173   孙熙凯
6    18688880441   沈晓雯
7    18688880651   苗泽坤
8    18688880212   李达明
9    18688880272   陈有浩
10   18688880466   沈丹丹
11   18688880279    胡煜
12   18688880419   徐骏太
13   18688880792   高僖桐
14   18688880316    朱钰
15   18688880366   孙新潇
16   18688880654   牛长金
17   18688880412    赵英
18   18688880751   王嘉淏
19   18688880285   张芳语
20   18688880027   许和怡
21   18688880193   邵昱笑
22   18688880648   苗秋兰
23   18688880163   张靖雯
24   18688880005   莫子建
25   18688880649   苗家畅
26   18688880009   张馥雨
27   18688880198   康雅欣
28   18688880317   周子轩
29   18688880011   姜晗昱
..           ...   ...
916  18688880307   任红娇
917  18688880009   张馥雨
918  18688880231   张大鹏
919  18688880120    陆涛
920  18688880104   任文琪
921  18688880110    陶璐
922  18688880108   卓艳妍
923  18688880111    黄哲
924  18688880312   李佩珊
925  18688880305   王静宇
926  18688880101   赵玉倩
927  18688880201    赵倩
928  18688880329    卢玲
929  18688880010   麦凯泽
930  18688880096   姜妮妮
931  18688880040   叶潇逸
932  18688880208   原程心
933  18688880015   张昭阳
934  18688880318   余思言
935  18688880121   方祥文
936  18688880110   关凯月
937  18688880119    夏雪
938  18688880215   黄青芸
939  18688880304   张小雨
940  18688880108    陈宇
941  18688880307    李靖
942  18688880305    莫言
943  18688880327   习一冰
944  18688880207   章春华
945  18688880313   唐雅嘉

[946 rows x 21 columns]

In [9]:
order4 = pd.read_csv('./exe/meal_order_info.csv',
                    sep=',',encoding='utf-8')

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 0: invalid continuation byte

In [12]:
import os
print('写入csv前:',os.listdir('./exe'))
order.to_csv('./exe/orderInfo.csv',sep=';',index=False)
print('写入后读取',os.listdir('./exe'))

写入csv前: ['meal_order_detail.xlsx', 'meal_order_detail1.sql', 'meal_order_detail2.sql', 'meal_order_detail3.sql', 'meal_order_info.csv', 'users.xlsx', '数据特征说明.xlsx']
写入后读取 ['meal_order_detail.xlsx', 'meal_order_detail1.sql', 'meal_order_detail2.sql', 'meal_order_detail3.sql', 'meal_order_info.csv', 'orderInfo.csv', 'users.xlsx', '数据特征说明.xlsx']

In [14]:
user = pd.read_excel('./exe/users.xlsx')
print(len(user))

734

In [15]:
# to_excel存储excel文件
print("写入前:",os.listdir('./exe'))
user.to_excel('./exe/userInfo.xlsx')
print('写入以后',os.listdir('./exe'))

写入前: ['meal_order_detail.xlsx', 'meal_order_detail1.sql', 'meal_order_detail2.sql', 'meal_order_detail3.sql', 'meal_order_info.csv', 'orderInfo.csv', 'users.xlsx', '数据特征说明.xlsx']
写入以后 ['meal_order_detail.xlsx', 'meal_order_detail1.sql', 'meal_order_detail2.sql', 'meal_order_detail3.sql', 'meal_order_info.csv', 'orderInfo.csv', 'userInfo.xlsx', 'users.xlsx', '数据特征说明.xlsx']

## DataFrame 基本操作

## 转换时间字符串为标准时间 4-41

In [19]:
import pandas as pd
order = pd.read_table('./exe/meal_order_info.csv',
                     sep=',',encoding='gbk')
print('转换前的lock_time类型：',order['lock_time'].dtypes)
order['lock_time'] = pd.to_datetime(order['lock_time'])
print('转换以后:',order['lock_time'].dtypes)

转换前的lock_time类型： object
转换以后: datetime64[ns]

In [20]:
print('最小时间：',pd.Timestamp.min)

最小时间： 1677-09-21 00:12:43.145225

In [21]:
print('最大时间：',pd.Timestamp.max)

最大时间： 2262-04-11 23:47:16.854775807

## 字符串转化对应数据关系索引值

In [22]:
dateIndex = pd.DatetimeIndex(order['lock_time'])
print('转换DatetimeIndex之后数据的类型',type(dateIndex))

转换DatetimeIndex之后数据的类型 <class 'pandas.core.indexes.datetimes.DatetimeIndex'>

In [24]:
periodIndex = pd.PeriodIndex(order['lock_time'],freq='S')
print("转换为PeriodIndex之后的数据的类型",type(periodIndex))

转换为PeriodIndex之后的数据的类型 <class 'pandas.core.indexes.period.PeriodIndex'>

## 提取datetime数据中的时间序列数据

In [25]:
year1 = [i.year for i in order['lock_time']]
print('lock_time中的年份数据前5个位：',year1[:5])

lock_time中的年份数据前5个位： [2016, 2016, 2016, 2016, 2016]

In [26]:
month1 = [i.month for i in order['lock_time']]
print('lock_time中的月份数据前五个位：',month1[:5])

lock_time中的月份数据前五个位： [8, 8, 8, 8, 8]

In [27]:
weekday1 = [i.weekday_name for i in order['lock_time']]
print('lock_time中星期名称数据前5个为：',weekday1[:5])

lock_time中星期名称数据前5个为： ['Monday', 'Monday', 'Monday', 'Monday', 'Monday']

In [28]:
print('dataIndex中星期名称数据前5个位：',dateIndex.weekday_name[:5])
print('periodIndex中的星期标号数据的前5个数据为：',periodIndex.weekday[:5])

dataIndex中星期名称数据前5个位： Index(['Monday', 'Monday', 'Monday', 'Monday', 'Monday'], dtype='object', name='lock_time')
periodIndex中的星期标号数据的前5个数据为： Int64Index([0, 0, 0, 0, 0], dtype='int64', name='lock_time')

## 加减时间

In [29]:
time1 = order['lock_time'] + pd.Timedelta(days = 1)
print('lock_time加上一天前前5数据：',order['lock_time'][:5])
print('lock_time加上一天前前5行数据为：',time1[:5])

lock_time加上一天前前5数据： 0   2016-08-01 11:11:46
1   2016-08-01 11:31:55
2   2016-08-01 12:54:37
3   2016-08-01 13:08:20
4   2016-08-01 13:07:16
Name: lock_time, dtype: datetime64[ns]
lock_time加上一天前前5行数据为： 0   2016-08-02 11:11:46
1   2016-08-02 11:31:55
2   2016-08-02 12:54:37
3   2016-08-02 13:08:20
4   2016-08-02 13:07:16
Name: lock_time, dtype: datetime64[ns]

In [33]:
timeDelta = order['lock_time'] - pd.to_datetime('2017-1-1')
print(timeDelta[:5])
print('lock_time减去2017年1月1日0.0.0:',timeDelta.dtypes)

0   -153 days +11:11:46
1   -153 days +11:31:55
2   -153 days +12:54:37
3   -153 days +13:08:20
4   -153 days +13:07:16
Name: lock_time, dtype: timedelta64[ns]
lock_time减去2017年1月1日0.0.0: timedelta64[ns]

In [ ]:
## 续借4-48